---
# Copyright 2016, JinkIT, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- stat: path={{osad_confdir}}
  register: osad_confdir_exists
  when: inventory_hostname in groups['deploy']
  tags:
    - osad-config

- name: generate ssh keys for the deployment host
  command: cp /opt/openstack-ansible/etc/openstack_deploy "{{osad_confdir}}"
  when: (inventory_hostname in groups['deploy'] and osad_confdir_exists.stat.exists  == False)
  tags:
    - osad-config

- name: configure networking
  template:
    src: template/openstack_user_config.yml.j2
    dest: "{{osad_confdir}}"/openstack_user_config.yml.j2
    backup: yes
  when: inventory_hostname in groups['deploy']
  tags:
    - osad-config

- name: configure networking
  template:
    src: template/user_variables.yml.j2
    dest: "{{osad_confdir}}"/user_variables.yml.j2
    backup: yes
  when: inventory_hostname in groups['deploy']
  tags:
    - osad-config
